name: CI

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

     steps:
     - name: Build Linux Container Image and Push to ACR

       on:
        workflow_dispatch:

      jobs:
        build:
          runs-on: ubuntu-latest
          defaults:
            run:
              shell: bash
              working-directory: dotnet
          steps:
          - uses: actions/checkout@v2
          - uses: azure/docker-login@v1
            with:
              login-server: myacrrr.azurecr.io
              username: ${{ secrets.REGISTRY_USERNAME }}
              password: ${{ secrets.REGISTRY_PASSWORD }}
          - run: |
              docker build . -t myacrrr.azurecr.io/myapp:${{ github.sha }}
              docker push myacrrr.azurecr.io/myapp:${{ github.sha }}
    
