name: CI

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
            run:
              shell: bash
              working-directory: dotnet
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Azure Docker Login
      uses: azure/docker-login@v1
      with:
        login-server: myacrrr.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Build and Push Docker Image
      run: |
        docker build . -t myacrrr.azurecr.io/myapp:${{ github.sha }}
        docker push myacrrr.azurecr.io/myapp:${{ github.sha }}
